inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  Exclude:
    - 'coverage/**/*'
    - 'etc/**/*'
    - 'pkg/**/*'
    - 'rdoc/**/*'
    - 'test/data/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

# Settings for line length
Layout/LineLength:
  URISchemes: http, https, ftp
