AllCops:
  NewCops: disable
  DisabledByDefault: true
  Exclude:                      # Directories excluded from RuboCop checks
    - 'coverage/**/*'
    - 'etc/**/*'
    - 'pkg/**/*'
    - 'rdoc/**/*'
    - 'test/data/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

Lint/Syntax:
  Enabled: true
