inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  Exclude:
    - 'coverage/**/*'
    - 'etc/**/*'
    - 'pkg/**/*'
    - 'rdoc/**/*'
    - 'test/data/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

# Settings for line length
Layout/LineLength:
  URISchemes: http, https, ftp

# Workaround for RuboCop bug.
# It have already been fixed in the HEAD of RuboCop.
# Remove after new release version.
# https://github.com/rubocop/rubocop/issues/14528
Style/RedundantFormat:
  Exclude:
    - 'lib/bio/io/flatfile/index.rb'
