# .rubocop.yml
<% unless ENV['BYPASS_RUBOCOP_TODO'] %>
inherit_from: .rubocop_todo.yml
<% end %>

AllCops:
  NewCops: enable
  Exclude:
    - 'coverage/**/*'
    - 'etc/**/*'
    - 'pkg/**/*'
    - 'rdoc/**/*'
    - 'test/data/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

# Settings for line length
Layout/LineLength:
  URISchemes: http, https, ftp

# Comments put on the same line as some keywords (class, module, def,
# begin, end) shoud be allowed, especially for comments after "end"
# that mention corresponding starting points of the "end".
Style/CommentedKeyword:
  Enabled: false

# Workaround for RuboCop bug.
# It have already been fixed in the HEAD of RuboCop.
# Remove after new release version.
# https://github.com/rubocop/rubocop/issues/14528
Style/RedundantFormat:
  Exclude:
    - 'lib/bio/io/flatfile/index.rb'
