---
version: "{build}"
image: Visual Studio 2019
branches:
  only:
    - master
    - incoming
clone_depth: 10
install:
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - bundle config set --local path vendor\bundle
  - bundle install --retry 5 --jobs=%NUMBER_OF_PROCESSORS%
build: off
before_test:
  - ruby --version
  - gem --version
  - bundle --version
test_script:
  - bundle exec rake
environment:
  matrix:
    - ruby_version: "27"
    - ruby_version: "27-x64"
    - ruby_version: "30"
    - ruby_version: "30-x64"
    - ruby_version: "31"
#    - ruby_version: "31-x64"
cache:
# If one of the files after the right arrow changes, cache will be invalidated
  - 'vendor\bundle -> appveyor.yml,Gemfile,bioruby.gemspec'
