# Type signatures for Bio::Feature class

module Bio
  class Feature
    include Enumerable[Qualifier]

    attr_accessor feature: String
    attr_accessor position: String
    attr_accessor qualifiers: Array[Qualifier]

    def initialize: (?String feature, ?String position, ?Array[Qualifier] qualifiers) -> void
    def locations: () -> Locations
    def append: (Qualifier qualifier) -> self
    def each: (?String? key) { (Qualifier) -> void } -> void
    def assoc: () -> Hash[String, String]
    def to_hash: () -> Hash[String, Array[String]]
    def []: (String key) -> Array[String]?

    class Qualifier
      attr_reader qualifier: String
      attr_reader value: String

      def initialize: (String key, String value) -> void
    end
  end
end
