#!/usr/bin/env ruby 
#
# dbget - DBGET client
#
#  Interface to GenomeNet DBGET system - http://www.genome.ad.jp/dbget/
#
#   Copyright (C) 2001 KATAYAMA Toshiaki <k@bioruby.org>
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  $Id: dbget,v 1.2 2001/08/23 00:50:07 katayama Exp $
#
#  ChangeLog:
#    2001/01/29 v1.0 (k)
#    2001/02/20 v1.1 (k) GPL
#

require "bio/io/dbget"

# Uncomment to enable bget(), bfind(), btit() etc. as module functions
#include DBGET

# DBGET command
com = $0.sub(".*/", '')			# e.g. $PATH/bget db entry
com = $*.shift if com == "dbget"	# e.g. $PATH/dbget bget db entry

# DBGET query strings
arg = $*.join(" ")

# DBGET result
print DBGET::dbget(com, arg)

