# Type signatures for the main Bio module

module Bio
  # Version constants
  BIORUBY_VERSION: Array[Integer]
  BIORUBY_EXTRA_VERSION: String?
  BIORUBY_VERSION_ID: String

  class Pathway
  end

  class Relation
  end
end
