name: Unit Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        ruby: [ '2.0', '2.1', '2.2', '2.3', '2.4', 2.5', '2.6' ]
    name: Ruby version ${{ matrix.ruby }} tests
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: bundle install && rake test
