#
# References: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [ "master", "incoming" ]
  pull_request:
    branches: [ "master", "incoming" ]

permissions:
  contents: read

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-22.04, windows-latest]
        ruby-version: ['2.7', '3.0', '3.1', '3.2', '3.3', head, jruby, jruby-head]
        exclude:
          - os: windows-latest
            ruby-version: head
          - os: windows-latest
            ruby-version: jruby
          - os: windows-latest
            ruby-version: jruby-head
    runs-on: ${{ matrix.os }}
    steps:
    - name: Configure git (Windows)
      if: runner.os == 'Windows'
      run: git config --global core.autocrlf false
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Run tests
      run: bundle exec rake
